from .test_favorite_activity import TestFavoriteActivity
from .test_main_goal_of_exercising import TestMainGoalOfExercising
from .test_overall_I_like_activities import TestOverallILikeActivities
from .test_what_is_your_age_group import TestWhatIsYourAgeGroup
from .test_when_do_you_like_to_exercise import TestWhenDoYouLikeToExercise
