# Generated by Django 4.0.3 on 2022-03-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_terms'),
        ('api', '0002_session'),
    ]

    operations = [
    ]
